database:
  user: flower_secret:pg_pass
  host: flower_secret:pg_host
  port: flower_secret:pg_port
  password: flower_secret:pg_pass
  db_name: flowers_core

notificator:
  url: flower_secret:url
  telebot: flower_secret:token
  recipient: flower_secret:recipient